### PR TITLE
Add some unit tests to the project to improve coverage

### LINKED ISSUE #38: Write unit tests
Pretty self explainatory, must be done after Travis CI is set (not really sure if that's true).

### PR DESCRIPTION
**Pull request by svenharris**
Added some unit tests which can be run locally prior to Travis CI being set up.

Closes #38

### CODE REVIEW

**Comment by LTKills** [comment]
Thanks for your contribution, unfortunately I figured that this should be done after #37 is completed. You could work on that if you want. To avoid doing work that is invalid always be sure to 
- Check the repo's contributing instructions
- Make sure the issue is clear (discuss possible doubts you have) and assigned to you
before submitting a PR

**Comment by svenharris** [comment]
As mentioned in my comment, it is normal for a project to have unit tests before being set up on a CI platform. These tests will run locally on the developer's machine and ensure the quality of the code. I am unsure why you have added the restriction of this happening after Travis CI being set up

**Comment by LTKills** [comment]
The problem is not the CI not being set up, but the code refactoring. If I include this changes now, they would need to be done again after the code is refactored

**Comment by svenharris** [comment]
Ok sure, of course it is your choice but again I would say it's common practice to write tests and then rewrite them as your code base changes, so would encourage to get some in there as soon as poss to get some confidence on code quality

**Comment by LTKills** [comment]
Yeah I agree with you, otherwise we would never write any tests because code is always changing. I'll look this up later today

**Pull request closed without merging**
